@startuml Diagramme de classe

hide circle
skinparam classAttributeIconSize 0

class Produit {
    -int codebarre
    -string nom
    -string description
    -float price
    -float poids
    -float volume    
}

class InterfaceDisponibiliteProduit {
    -int emplacement
}
class Creneau {
    -date Date
    -int capacité    
}

class Panier {
    +ajouterProduit(produit, quantité)
    +modifierPanier(produit, quantité)
    +SupprimerProduit(produit)
}

class Commande {
    +retirerProduit(produit)
    +modifierProduit(produit,nouveauProduit)
}

class Visiteur implements Consultation{
    +login(identifiant, mdp)
    +sélectionnerMagasin(localisationGPS)
    +communiquerChatbot()
}

class Client extends Visiteur {
    -identité
    -email
    -localisation
    +choisirCreneau(creneau)
    +passerCommande(panier)
    +consulterProfil()
    +choisirMagasinFavori(magasin)
    +créerListeDeCourses()
    +modifierListeDeCourses(listeDeCourse)
    +supprimerListeDeCourses(listeDeCourse)
    +ajouterUnProduitFavori(produit)
    +supprimerProduitFavori(produit)
    +retirerCommande(commande)
}

class Admin extends Visiteur {
    -identité
    -email
    +ajouterProduitCatalogue(produit)
    +modifierProduit(produit,nouveauProduit)
    +supprimerProduit(produit)
}

class Préparateur implements Consultation {
    -identité
    -email
    +scannerProduit(produit)
    +validerPreparationCommande(commande)    
}

class Magasin {

}

class Rayon {

}

class ListeDeCourses {

}

interface Consultation {
    +consulterPanier(panier)
    +consulterCatalogue(typeCatalogue, magasin)
    +consulterProduit(produit, magasin)
    +rechercherProduit(parametresRecherche)
}

Produit "0..*" --> "0..1" Panier
Produit "0..*" --> "0..1" Commande
Client "1" --> "0..*"  Commande
Client "1" --> "1" Panier
Produit "0..*"--> "0..*" Magasin
Préparateur "0..1" --> "0..*" Commande
Produit "0..*" --> "1" Rayon
Magasin "0..*" --> "0..*" Rayon
Commande "0..10" --> "1" Creneau
Client "0..*"--> "0..1" Magasin
ListedeCourses "0..*" --> "1" Client
ListeDeCourses "0..*" --> "0..*" Produit
Client "0..*" --> "0..*" Produit
Préparateur "0..*" --> "1..*" Magasin



@enduml