@startuml Usecase

scale 0.75

:Visiteur: as V
:Client: as C
:Préparateur: as P
:Admnistrateur: as Ad

agent "Service de notification" <<actor>> as ServiceNotif

C -|> V
Ad -|> V

rectangle DRIVE {

package Consultation {
(Rechercher un produit) as RechercherProduit
(Consulter le catalogue Global) as ConsulterCatalogueGlobal
(Consulter le catalogue d'un rayon) as ConsulterRayon
(Consulter le catalogue d'un magasin) as ConsulterCatalogueMagasin
(Consulter un produit) as ConsulterProduit
}

package EspaceClient {
(Passer une commande) as PasserCommande
(Consulter son Profil) as ConsulterProfil
(Choisir/Modifier le magasin favori) as ChoisirMagasinFavoris
(Gérer produit favori) as GererProduitsFavoris
(Gérer liste de courses) as GererListeCourses
(Choisir/Modifier son créneau) as ChoisirCreneau
(Gérer ses coordonnées) as GererCoordonnees
(Retirer Commande) as RetirerCommande
(Annuler Commande) as AnnulerCommande
}


package Admin {
(Gérer bons de réduction) as GererBonsReduction
(ModifierCommande) as ModifierCommande
(Gérer les produits) as GérerProduits
}

package ActionSiteWeb {
(Selectionner/Modifier Magasin) as SelectionMagasin
(S'authentifier) as Auth
(Gérer le panier) as GererPanier
(Communiquer avec le chatbot) as CommunicationChatBot
}

(Consulter les commandes) as ConsulterCommandes

package Preparateur {
(Scanner produit) as ScannerProduit
(Confirmer validation commande) as ValiderPrepCommande
}

(Notification Client) as NotifClient

}



left to right direction
V -- Consultation
V -- ActionSiteWeb

SelectionMagasin ..> ConsulterCatalogueMagasin  #red : include
SelectionMagasin ..> ConsulterRayon  #red : include

Auth <.. C #red : include

NotifClient -- ServiceNotif
NotifClient --> C


C -- EspaceClient
C -- ActionSiteWeb

RetirerCommande ..> PasserCommande #red:include


P ..> ConsulterCommandes #red : include
P -- Consultation
P -- Preparateur



Ad -- Admin
Ad -- ConsulterCommandes






@enduml